version: '3'

services:
  database:
    image: mysql:${MYSQL_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}_database
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ${MYSQL_DATA:-./db_data}:/var/lib/mysql
    networks:
      - nextjs_wp

  phpmyadmin:
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    links:
      - database
    ports:
      - 8080:80
    depends_on:
      - database
    networks:
      - nextjs_wp

  wordpress:
    image: wordpress:${WORDPRESS_VERSION:-latest}
    container_name: ${COMPOSE_PROJECT_NAME}_wordpress
    restart: always
    ports:
      - 9000:80
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - database
    volumes:
      - ${WORDPRESS_DATA:-./backend}:/var/www/html
    networks:
      - nextjs_wp
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./backend:/var/www/html

  next-app:
    container_name: ${COMPOSE_PROJECT_NAME:-icd-vn}_next-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: 1
    ports:
      - 3000:3000
    volumes:
      - ${NEXT_DATA:-./frontend}:/usr/src/app
    depends_on:
      - database
      - wordpress
    command: npm run dev
    restart: always
    networks:
      - nextjs_wp

networks:
  nextjs_wp:
    driver: bridge
